import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";

export async function POST(req: NextRequest): Promise<NextResponse> {
  let body: {
    host?: string;
    port?: string | number;
    username?: string;
    password?: string;
    testPath?: string;
  };

  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { status: "error", message: "Invalid JSON body" },
      { status: 400 },
    );
  }

  const { host, port, username, password, testPath } = body;

  if (!host || !username) {
    return NextResponse.json(
      { status: "error", message: "host and username are required." },
      { status: 400 },
    );
  }

  // Dynamically require ssh2 so the rest of the app works even without it.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  interface SshClient {
    connect(opts: object): void;
    sftp(cb: (err: Error | null, sftp: SftpSession) => void): void;
    end(): void;
    destroy(): void;
    on(event: string, cb: (...args: unknown[]) => void): SshClient;
  }
  let ssh2Module: { Client: new () => SshClient };

  try {
    ssh2Module = require("ssh2");
  } catch {
    return NextResponse.json(
      {
        status: "error",
        message:
          "ssh2 package is not installed on the server. " +
          "Run: npm install ssh2  then restart the dev server.",
      },
      { status: 500 },
    );
  }

  interface WriteStream {
    on(event: string, cb: (...args: unknown[]) => void): WriteStream;
    write(data: Buffer): void;
    end(data?: Buffer): void;
  }
  interface SftpSession {
    createWriteStream(path: string): WriteStream;
    unlink(path: string, cb: (err: Error | null) => void): void;
  }

  const start = Date.now();

  const result = await new Promise<{
    status: string;
    message: string;
    latencyMs?: number;
  }>((resolve) => {
    const { Client } = ssh2Module;
    const conn = new Client();

    const timer = setTimeout(() => {
      try {
        conn.destroy();
      } catch {
        /* noop */
      }
      resolve({ status: "error", message: "Connection timed out after 10 s." });
    }, 10_000);

    conn
      .on("ready", () => {
        conn.sftp((err, sftp) => {
          if (err) {
            clearTimeout(timer);
            conn.end();
            resolve({
              status: "error",
              message: `SFTP subsystem error: ${err.message}`,
            });
            return;
          }

          const cleanPath = (testPath || "/").replace(/\/+$/, "") || "/";
          const uploadPath = `${cleanPath}/.sfg-health-${Date.now()}.tmp`;
          const content = Buffer.from(
            `SFG Health Check\nTimestamp: ${new Date().toISOString()}\nGenerated by: Sterling Easy Web\n`,
          );

          const ws = sftp.createWriteStream(uploadPath);

          ws.on("error", (e: unknown) => {
            clearTimeout(timer);
            conn.end();
            const msg = e instanceof Error ? e.message : String(e);
            resolve({ status: "error", message: `Upload failed: ${msg}` });
          });

          ws.on("close", () => {
            sftp.unlink(uploadPath, () => {
              clearTimeout(timer);
              conn.end();
              resolve({
                status: "connected",
                message: `Connected to ${host}:${port ?? 22}. Test file uploaded and removed successfully.`,
                latencyMs: Date.now() - start,
              });
            });
          });

          ws.end(content);
        });
      })
      .on("error", (err: unknown) => {
        clearTimeout(timer);
        const msg = err instanceof Error ? err.message : String(err);
        resolve({ status: "error", message: msg });
      })
      .connect({
        host,
        port: Number(port) || 22,
        username,
        password,
        readyTimeout: 8_000,
        // Accept any host key for a health-check tool
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        hostVerifier: (_: unknown) => true,
      });
  });

  if (result.status === "error") {
    return NextResponse.json(result, { status: 500 });
  }

  return NextResponse.json(result);
}
